#!/bin/sh
INPUT=$1
EXITVAL="0"
RESULTS=.test.results
# use "FIFO LRU" unless environment variable ENVALGS is set
ALGS="${ENVALGS:-FIFO LRU}"
# use "" unless environment variable ENVFLAGS is set
FLAGS="${ENVFLAGS:-}"
for ALG in ${ALGS}; do
    echo "========="
    CMD="./vm ${FLAGS} ${ALG} ${INPUT}"
    echo "running $CMD"
    OUTPUT=${INPUT}.${ALG}${FLAGS}
    CORRECT=${OUTPUT}.correct
    MYOUTPUT=${OUTPUT}.myoutput
    cp correct_answers/${CORRECT} .
    TAILLINES=`wc -l < ${CORRECT} | awk '{print $1}'`
    ./vm ${FLAGS} $ALG $INPUT > ${MYOUTPUT}
    tail -${TAILLINES} ${MYOUTPUT} > ${MYOUTPUT}.tail
    echo "Running diff on the last ${TAILLINES} lines of your file '<correct >myoutput'"
    if diff -q ${CORRECT} ${MYOUTPUT}.tail; then
        echo "+++ PASSES   $CMD" | tee -a ${RESULTS}
    else
        diff ${CORRECT} ${MYOUTPUT}.tail | cat -vet
        echo "--- FAILS   $CMD"  | tee -a ${RESULTS}
        EXITVAL="1"
    fi
done
exit ${EXITVAL}
